/* All Countries for MySQL
 * Generated 2023-11-08
 * https://www.html-code-generator.com/mysql/country-name-table  
 */

CREATE TABLE IF NOT EXISTS `countries` (
    `country_id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(100) NOT NULL,
    `code_2` char(2) NOT NULL,
    `code_3` char(3) DEFAULT NULL,
    `phone_prefix` int(5) NOT NULL,
    `currency` varchar(3) DEFAULT NULL,
    `currency_symbol` varchar(10) DEFAULT NULL,
    `capital` varchar(80) DEFAULT NULL,
    PRIMARY KEY (`country_id`)
) ENGINE=InnoDB AUTO_INCREMENT=253 DEFAULT CHARSET=utf8;


INSERT INTO `countries` (`country_id`, `name`, `code_2`, `code_3`, `phone_prefix`, `currency`, `currency_symbol`, `capital`) VALUES
(1, 'Afghanistan', 'AF', 'AFG', 93, 'AFN', '؋', 'Kabul'),
(2, 'Aland Islands', 'AX', 'ALA', 358, 'EUR', '€', 'Mariehamn'),
(3, 'Albania', 'AL', 'ALB', 355, 'ALL', 'Lek', 'Tirana'),
(4, 'Algeria', 'DZ', 'DZA', 213, 'DZD', 'دج', 'Algiers'),
(5, 'American Samoa', 'AS', 'ASM', 1684, 'USD', '$', 'Pago Pago'),
(6, 'Andorra', 'AD', 'AND', 376, 'EUR', '€', 'Andorra la Vella'),
(7, 'Angola', 'AO', 'AGO', 244, 'AOA', 'Kz', 'Luanda'),
(8, 'Anguilla', 'AI', 'AIA', 1264, 'XCD', '$', 'The Valley'),
(9, 'Antarctica', 'AQ', 'ATA', 672, 'AAD', '$', 'Antarctica'),
(10, 'Antigua and Barbuda', 'AG', 'ATG', 1268, 'XCD', '$', 'St. John\'s'),
(11, 'Argentina', 'AR', 'ARG', 54, 'ARS', '$', 'Buenos Aires'),
(12, 'Armenia', 'AM', 'ARM', 374, 'AMD', '֏', 'Yerevan'),
(13, 'Aruba', 'AW', 'ABW', 297, 'AWG', 'ƒ', 'Oranjestad'),
(14, 'Australia', 'AU', 'AUS', 61, 'AUD', '$', 'Canberra'),
(15, 'Austria', 'AT', 'AUT', 43, 'EUR', '€', 'Vienna'),
(16, 'Azerbaijan', 'AZ', 'AZE', 994, 'AZN', 'm', 'Baku'),
(17, 'Bahamas', 'BS', 'BHS', 1242, 'BSD', 'B$', 'Nassau'),
(18, 'Bahrain', 'BH', 'BHR', 973, 'BHD', '.د.ب', 'Manama'),
(19, 'Bangladesh', 'BD', 'BGD', 880, 'BDT', '৳', 'Dhaka'),
(20, 'Barbados', 'BB', 'BRB', 1246, 'BBD', 'Bds$', 'Bridgetown'),
(21, 'Belarus', 'BY', 'BLR', 375, 'BYN', 'Br', 'Minsk'),
(22, 'Belgium', 'BE', 'BEL', 32, 'EUR', '€', 'Brussels'),
(23, 'Belize', 'BZ', 'BLZ', 501, 'BZD', '$', 'Belmopan'),
(24, 'Benin', 'BJ', 'BEN', 229, 'XOF', 'CFA', 'Porto-Novo'),
(25, 'Bermuda', 'BM', 'BMU', 1441, 'BMD', '$', 'Hamilton'),
(26, 'Bhutan', 'BT', 'BTN', 975, 'BTN', 'Nu.', 'Thimphu'),
(27, 'Bolivia', 'BO', 'BOL', 591, 'BOB', 'Bs.', 'Sucre'),
(28, 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', 599, 'USD', '$', 'Kralendijk'),
(29, 'Bosnia and Herzegovina', 'BA', 'BIH', 387, 'BAM', 'KM', 'Sarajevo'),
(30, 'Botswana', 'BW', 'BWA', 267, 'BWP', 'P', 'Gaborone'),
(31, 'Bouvet Island', 'BV', 'BVT', 55, 'NOK', 'kr', ''),
(32, 'Brazil', 'BR', 'BRA', 55, 'BRL', 'R$', 'Brasilia'),
(33, 'British Indian Ocean Territory', 'IO', 'IOT', 246, 'USD', '$', 'Diego Garcia'),
(34, 'Brunei Darussalam', 'BN', 'BRN', 673, 'BND', 'B$', 'Bandar Seri Begawan'),
(35, 'Bulgaria', 'BG', 'BGR', 359, 'BGN', 'Лв.', 'Sofia'),
(36, 'Burkina Faso', 'BF', 'BFA', 226, 'XOF', 'CFA', 'Ouagadougou'),
(37, 'Burundi', 'BI', 'BDI', 257, 'BIF', 'FBu', 'Bujumbura'),
(38, 'Cambodia', 'KH', 'KHM', 855, 'KHR', 'KHR', 'Phnom Penh'),
(39, 'Cameroon', 'CM', 'CMR', 237, 'XAF', 'FCFA', 'Yaounde'),
(40, 'Canada', 'CA', 'CAN', 1, 'CAD', '$', 'Ottawa'),
(41, 'Cape Verde', 'CV', 'CPV', 238, 'CVE', '$', 'Praia'),
(42, 'Cayman Islands', 'KY', 'CYM', 1345, 'KYD', '$', 'George Town'),
(43, 'Central African Republic', 'CF', 'CAF', 236, 'XAF', 'FCFA', 'Bangui'),
(44, 'Chad', 'TD', 'TCD', 235, 'XAF', 'FCFA', 'N\'Djamena'),
(45, 'Chile', 'CL', 'CHL', 56, 'CLP', '$', 'Santiago'),
(46, 'China', 'CN', 'CHN', 86, 'CNY', '¥', 'Beijing'),
(47, 'Christmas Island', 'CX', 'CXR', 61, 'AUD', '$', 'Flying Fish Cove'),
(48, 'Cocos (Keeling) Islands', 'CC', 'CCK', 672, 'AUD', '$', 'West Island'),
(49, 'Colombia', 'CO', 'COL', 57, 'COP', '$', 'Bogota'),
(50, 'Comoros', 'KM', 'COM', 269, 'KMF', 'CF', 'Moroni'),
(51, 'Congo', 'CG', 'COG', 242, 'XAF', 'FC', 'Brazzaville'),
(52, 'Congo, Democratic Republic of the Congo', 'CD', 'COD', 242, 'CDF', 'FC', 'Kinshasa'),
(53, 'Cook Islands', 'CK', 'COK', 682, 'NZD', '$', 'Avarua'),
(54, 'Costa Rica', 'CR', 'CRI', 506, 'CRC', '₡', 'San Jose'),
(55, 'Cote D\'Ivoire', 'CI', 'CIV', 225, 'XOF', 'CFA', 'Yamoussoukro'),
(56, 'Croatia', 'HR', 'HRV', 385, 'HRK', 'kn', 'Zagreb'),
(57, 'Cuba', 'CU', 'CUB', 53, 'CUP', '$', 'Havana'),
(58, 'Curacao', 'CW', 'CUW', 599, 'ANG', 'ƒ', 'Willemstad'),
(59, 'Cyprus', 'CY', 'CYP', 357, 'EUR', '€', 'Nicosia'),
(60, 'Czech Republic', 'CZ', 'CZE', 420, 'CZK', 'Kč', 'Prague'),
(61, 'Denmark', 'DK', 'DNK', 45, 'DKK', 'Kr.', 'Copenhagen'),
(62, 'Djibouti', 'DJ', 'DJI', 253, 'DJF', 'Fdj', 'Djibouti'),
(63, 'Dominica', 'DM', 'DMA', 1767, 'XCD', '$', 'Roseau'),
(64, 'Dominican Republic', 'DO', 'DOM', 1809, 'DOP', '$', 'Santo Domingo'),
(65, 'Ecuador', 'EC', 'ECU', 593, 'USD', '$', 'Quito'),
(66, 'Egypt', 'EG', 'EGY', 20, 'EGP', 'ج.م', 'Cairo'),
(67, 'El Salvador', 'SV', 'SLV', 503, 'USD', '$', 'San Salvador'),
(68, 'Equatorial Guinea', 'GQ', 'GNQ', 240, 'XAF', 'FCFA', 'Malabo'),
(69, 'Eritrea', 'ER', 'ERI', 291, 'ERN', 'Nfk', 'Asmara'),
(70, 'Estonia', 'EE', 'EST', 372, 'EUR', '€', 'Tallinn'),
(71, 'Ethiopia', 'ET', 'ETH', 251, 'ETB', 'Nkf', 'Addis Ababa'),
(72, 'Falkland Islands (Malvinas)', 'FK', 'FLK', 500, 'FKP', '£', 'Stanley'),
(73, 'Faroe Islands', 'FO', 'FRO', 298, 'DKK', 'Kr.', 'Torshavn'),
(74, 'Fiji', 'FJ', 'FJI', 679, 'FJD', 'FJ$', 'Suva'),
(75, 'Finland', 'FI', 'FIN', 358, 'EUR', '€', 'Helsinki'),
(76, 'France', 'FR', 'FRA', 33, 'EUR', '€', 'Paris'),
(77, 'French Guiana', 'GF', 'GUF', 594, 'EUR', '€', 'Cayenne'),
(78, 'French Polynesia', 'PF', 'PYF', 689, 'XPF', '₣', 'Papeete'),
(79, 'French Southern Territories', 'TF', 'ATF', 262, 'EUR', '€', 'Port-aux-Francais'),
(80, 'Gabon', 'GA', 'GAB', 241, 'XAF', 'FCFA', 'Libreville'),
(81, 'Gambia', 'GM', 'GMB', 220, 'GMD', 'D', 'Banjul'),
(82, 'Georgia', 'GE', 'GEO', 995, 'GEL', 'ლ', 'Tbilisi'),
(83, 'Germany', 'DE', 'DEU', 49, 'EUR', '€', 'Berlin'),
(84, 'Ghana', 'GH', 'GHA', 233, 'GHS', 'GH₵', 'Accra'),
(85, 'Gibraltar', 'GI', 'GIB', 350, 'GIP', '£', 'Gibraltar'),
(86, 'Greece', 'GR', 'GRC', 30, 'EUR', '€', 'Athens'),
(87, 'Greenland', 'GL', 'GRL', 299, 'DKK', 'Kr.', 'Nuuk'),
(88, 'Grenada', 'GD', 'GRD', 1473, 'XCD', '$', 'St. George\'s'),
(89, 'Guadeloupe', 'GP', 'GLP', 590, 'EUR', '€', 'Basse-Terre'),
(90, 'Guam', 'GU', 'GUM', 1671, 'USD', '$', 'Hagatna'),
(91, 'Guatemala', 'GT', 'GTM', 502, 'GTQ', 'Q', 'Guatemala City'),
(92, 'Guernsey', 'GG', 'GGY', 44, 'GBP', '£', 'St Peter Port'),
(93, 'Guinea', 'GN', 'GIN', 224, 'GNF', 'FG', 'Conakry'),
(94, 'Guinea-Bissau', 'GW', 'GNB', 245, 'XOF', 'CFA', 'Bissau'),
(95, 'Guyana', 'GY', 'GUY', 592, 'GYD', '$', 'Georgetown'),
(96, 'Haiti', 'HT', 'HTI', 509, 'HTG', 'G', 'Port-au-Prince'),
(97, 'Heard Island and Mcdonald Islands', 'HM', 'HMD', 0, 'AUD', '$', ''),
(98, 'Holy See (Vatican City State)', 'VA', 'VAT', 39, 'EUR', '€', 'Vatican City'),
(99, 'Honduras', 'HN', 'HND', 504, 'HNL', 'L', 'Tegucigalpa'),
(100, 'Hong Kong', 'HK', 'HKG', 852, 'HKD', '$', 'Hong Kong'),
(101, 'Hungary', 'HU', 'HUN', 36, 'HUF', 'Ft', 'Budapest'),
(102, 'Iceland', 'IS', 'ISL', 354, 'ISK', 'kr', 'Reykjavik'),
(103, 'India', 'IN', 'IND', 91, 'INR', '₹', 'New Delhi'),
(104, 'Indonesia', 'ID', 'IDN', 62, 'IDR', 'Rp', 'Jakarta'),
(105, 'Iran, Islamic Republic of', 'IR', 'IRN', 98, 'IRR', '﷼', 'Tehran'),
(106, 'Iraq', 'IQ', 'IRQ', 964, 'IQD', 'د.ع', 'Baghdad'),
(107, 'Ireland', 'IE', 'IRL', 353, 'EUR', '€', 'Dublin'),
(108, 'Isle of Man', 'IM', 'IMN', 44, 'GBP', '£', 'Douglas, Isle of Man'),
(109, 'Israel', 'IL', 'ISR', 972, 'ILS', '₪', 'Jerusalem'),
(110, 'Italy', 'IT', 'ITA', 39, 'EUR', '€', 'Rome'),
(111, 'Jamaica', 'JM', 'JAM', 1876, 'JMD', 'J$', 'Kingston'),
(112, 'Japan', 'JP', 'JPN', 81, 'JPY', '¥', 'Tokyo'),
(113, 'Jersey', 'JE', 'JEY', 44, 'GBP', '£', 'Saint Helier'),
(114, 'Jordan', 'JO', 'JOR', 962, 'JOD', 'ا.د', 'Amman'),
(115, 'Kazakhstan', 'KZ', 'KAZ', 7, 'KZT', 'лв', 'Astana'),
(116, 'Kenya', 'KE', 'KEN', 254, 'KES', 'KSh', 'Nairobi'),
(117, 'Kiribati', 'KI', 'KIR', 686, 'AUD', '$', 'Tarawa'),
(118, 'Korea, Democratic People\'s Republic of', 'KP', 'PRK', 850, 'KPW', '₩', 'Pyongyang'),
(119, 'Korea, Republic of', 'KR', 'KOR', 82, 'KRW', '₩', 'Seoul'),
(120, 'Kosovo', 'XK', 'XKX', 383, 'EUR', '€', 'Pristina'),
(121, 'Kuwait', 'KW', 'KWT', 965, 'KWD', 'ك.د', 'Kuwait City'),
(122, 'Kyrgyzstan', 'KG', 'KGZ', 996, 'KGS', 'лв', 'Bishkek'),
(123, 'Lao People\'s Democratic Republic', 'LA', 'LAO', 856, 'LAK', '₭', 'Vientiane'),
(124, 'Latvia', 'LV', 'LVA', 371, 'EUR', '€', 'Riga'),
(125, 'Lebanon', 'LB', 'LBN', 961, 'LBP', '£', 'Beirut'),
(126, 'Lesotho', 'LS', 'LSO', 266, 'LSL', 'L', 'Maseru'),
(127, 'Liberia', 'LR', 'LBR', 231, 'LRD', '$', 'Monrovia'),
(128, 'Libyan Arab Jamahiriya', 'LY', 'LBY', 218, 'LYD', 'د.ل', 'Tripolis'),
(129, 'Liechtenstein', 'LI', 'LIE', 423, 'CHF', 'CHf', 'Vaduz'),
(130, 'Lithuania', 'LT', 'LTU', 370, 'EUR', '€', 'Vilnius'),
(131, 'Luxembourg', 'LU', 'LUX', 352, 'EUR', '€', 'Luxembourg'),
(132, 'Macao', 'MO', 'MAC', 853, 'MOP', '$', 'Macao'),
(133, 'Macedonia, the Former Yugoslav Republic of', 'MK', 'MKD', 389, 'MKD', 'ден', 'Skopje'),
(134, 'Madagascar', 'MG', 'MDG', 261, 'MGA', 'Ar', 'Antananarivo'),
(135, 'Malawi', 'MW', 'MWI', 265, 'MWK', 'MK', 'Lilongwe'),
(136, 'Malaysia', 'MY', 'MYS', 60, 'MYR', 'RM', 'Kuala Lumpur'),
(137, 'Maldives', 'MV', 'MDV', 960, 'MVR', 'Rf', 'Male'),
(138, 'Mali', 'ML', 'MLI', 223, 'XOF', 'CFA', 'Bamako'),
(139, 'Malta', 'MT', 'MLT', 356, 'EUR', '€', 'Valletta'),
(140, 'Marshall Islands', 'MH', 'MHL', 692, 'USD', '$', 'Majuro'),
(141, 'Martinique', 'MQ', 'MTQ', 596, 'EUR', '€', 'Fort-de-France'),
(142, 'Mauritania', 'MR', 'MRT', 222, 'MRO', 'MRU', 'Nouakchott'),
(143, 'Mauritius', 'MU', 'MUS', 230, 'MUR', '₨', 'Port Louis'),
(144, 'Mayotte', 'YT', 'MYT', 262, 'EUR', '€', 'Mamoudzou'),
(145, 'Mexico', 'MX', 'MEX', 52, 'MXN', '$', 'Mexico City'),
(146, 'Micronesia, Federated States of', 'FM', 'FSM', 691, 'USD', '$', 'Palikir'),
(147, 'Moldova, Republic of', 'MD', 'MDA', 373, 'MDL', 'L', 'Chisinau'),
(148, 'Monaco', 'MC', 'MCO', 377, 'EUR', '€', 'Monaco'),
(149, 'Mongolia', 'MN', 'MNG', 976, 'MNT', '₮', 'Ulan Bator'),
(150, 'Montenegro', 'ME', 'MNE', 382, 'EUR', '€', 'Podgorica'),
(151, 'Montserrat', 'MS', 'MSR', 1664, 'XCD', '$', 'Plymouth'),
(152, 'Morocco', 'MA', 'MAR', 212, 'MAD', 'DH', 'Rabat'),
(153, 'Mozambique', 'MZ', 'MOZ', 258, 'MZN', 'MT', 'Maputo'),
(154, 'Myanmar', 'MM', 'MMR', 95, 'MMK', 'K', 'Nay Pyi Taw'),
(155, 'Namibia', 'NA', 'NAM', 264, 'NAD', '$', 'Windhoek'),
(156, 'Nauru', 'NR', 'NRU', 674, 'AUD', '$', 'Yaren'),
(157, 'Nepal', 'NP', 'NPL', 977, 'NPR', '₨', 'Kathmandu'),
(158, 'Netherlands', 'NL', 'NLD', 31, 'EUR', '€', 'Amsterdam'),
(159, 'Netherlands Antilles', 'AN', 'ANT', 599, 'ANG', 'NAf', 'Willemstad'),
(160, 'New Caledonia', 'NC', 'NCL', 687, 'XPF', '₣', 'Noumea'),
(161, 'New Zealand', 'NZ', 'NZL', 64, 'NZD', '$', 'Wellington'),
(162, 'Nicaragua', 'NI', 'NIC', 505, 'NIO', 'C$', 'Managua'),
(163, 'Niger', 'NE', 'NER', 227, 'XOF', 'CFA', 'Niamey'),
(164, 'Nigeria', 'NG', 'NGA', 234, 'NGN', '₦', 'Abuja'),
(165, 'Niue', 'NU', 'NIU', 683, 'NZD', '$', 'Alofi'),
(166, 'Norfolk Island', 'NF', 'NFK', 672, 'AUD', '$', 'Kingston'),
(167, 'Northern Mariana Islands', 'MP', 'MNP', 1670, 'USD', '$', 'Saipan'),
(168, 'Norway', 'NO', 'NOR', 47, 'NOK', 'kr', 'Oslo'),
(169, 'Oman', 'OM', 'OMN', 968, 'OMR', '.ع.ر', 'Muscat'),
(170, 'Pakistan', 'PK', 'PAK', 92, 'PKR', '₨', 'Islamabad'),
(171, 'Palau', 'PW', 'PLW', 680, 'USD', '$', 'Melekeok'),
(172, 'Palestinian Territory, Occupied', 'PS', 'PSE', 970, 'ILS', '₪', 'East Jerusalem'),
(173, 'Panama', 'PA', 'PAN', 507, 'PAB', 'B/.', 'Panama City'),
(174, 'Papua New Guinea', 'PG', 'PNG', 675, 'PGK', 'K', 'Port Moresby'),
(175, 'Paraguay', 'PY', 'PRY', 595, 'PYG', '₲', 'Asuncion'),
(176, 'Peru', 'PE', 'PER', 51, 'PEN', 'S/.', 'Lima'),
(177, 'Philippines', 'PH', 'PHL', 63, 'PHP', '₱', 'Manila'),
(178, 'Pitcairn', 'PN', 'PCN', 64, 'NZD', '$', 'Adamstown'),
(179, 'Poland', 'PL', 'POL', 48, 'PLN', 'zł', 'Warsaw'),
(180, 'Portugal', 'PT', 'PRT', 351, 'EUR', '€', 'Lisbon'),
(181, 'Puerto Rico', 'PR', 'PRI', 1787, 'USD', '$', 'San Juan'),
(182, 'Qatar', 'QA', 'QAT', 974, 'QAR', 'ق.ر', 'Doha'),
(183, 'Reunion', 'RE', 'REU', 262, 'EUR', '€', 'Saint-Denis'),
(184, 'Romania', 'RO', 'ROM', 40, 'RON', 'lei', 'Bucharest'),
(185, 'Russian Federation', 'RU', 'RUS', 7, 'RUB', '₽', 'Moscow'),
(186, 'Rwanda', 'RW', 'RWA', 250, 'RWF', 'FRw', 'Kigali'),
(187, 'Saint Barthelemy', 'BL', 'BLM', 590, 'EUR', '€', 'Gustavia'),
(188, 'Saint Helena', 'SH', 'SHN', 290, 'SHP', '£', 'Jamestown'),
(189, 'Saint Kitts and Nevis', 'KN', 'KNA', 1869, 'XCD', '$', 'Basseterre'),
(190, 'Saint Lucia', 'LC', 'LCA', 1758, 'XCD', '$', 'Castries'),
(191, 'Saint Martin', 'MF', 'MAF', 590, 'EUR', '€', 'Marigot'),
(192, 'Saint Pierre and Miquelon', 'PM', 'SPM', 508, 'EUR', '€', 'Saint-Pierre'),
(193, 'Saint Vincent and the Grenadines', 'VC', 'VCT', 1784, 'XCD', '$', 'Kingstown'),
(194, 'Samoa', 'WS', 'WSM', 684, 'WST', 'SAT', 'Apia'),
(195, 'San Marino', 'SM', 'SMR', 378, 'EUR', '€', 'San Marino'),
(196, 'Sao Tome and Principe', 'ST', 'STP', 239, 'STD', 'Db', 'Sao Tome'),
(197, 'Saudi Arabia', 'SA', 'SAU', 966, 'SAR', '﷼', 'Riyadh'),
(198, 'Senegal', 'SN', 'SEN', 221, 'XOF', 'CFA', 'Dakar'),
(199, 'Serbia', 'RS', 'SRB', 381, 'RSD', 'din', 'Belgrade'),
(200, 'Serbia and Montenegro', 'CS', 'SCG', 381, 'RSD', 'din', 'Belgrade'),
(201, 'Seychelles', 'SC', 'SYC', 248, 'SCR', 'SRe', 'Victoria'),
(202, 'Sierra Leone', 'SL', 'SLE', 232, 'SLL', 'Le', 'Freetown'),
(203, 'Singapore', 'SG', 'SGP', 65, 'SGD', '$', 'Singapur'),
(204, 'Sint Maarten', 'SX', 'SXM', 721, 'ANG', 'ƒ', 'Philipsburg'),
(205, 'Slovakia', 'SK', 'SVK', 421, 'EUR', '€', 'Bratislava'),
(206, 'Slovenia', 'SI', 'SVN', 386, 'EUR', '€', 'Ljubljana'),
(207, 'Solomon Islands', 'SB', 'SLB', 677, 'SBD', 'Si$', 'Honiara'),
(208, 'Somalia', 'SO', 'SOM', 252, 'SOS', 'Sh.so.', 'Mogadishu'),
(209, 'South Africa', 'ZA', 'ZAF', 27, 'ZAR', 'R', 'Pretoria'),
(210, 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', 500, 'GBP', '£', 'Grytviken'),
(211, 'South Sudan', 'SS', 'SSD', 211, 'SSP', '£', 'Juba'),
(212, 'Spain', 'ES', 'ESP', 34, 'EUR', '€', 'Madrid'),
(213, 'Sri Lanka', 'LK', 'LKA', 94, 'LKR', 'Rs', 'Colombo'),
(214, 'Sudan', 'SD', 'SDN', 249, 'SDG', '.س.ج', 'Khartoum'),
(215, 'Suriname', 'SR', 'SUR', 597, 'SRD', '$', 'Paramaribo'),
(216, 'Svalbard and Jan Mayen', 'SJ', 'SJM', 47, 'NOK', 'kr', 'Longyearbyen'),
(217, 'Swaziland', 'SZ', 'SWZ', 268, 'SZL', 'E', 'Mbabane'),
(218, 'Sweden', 'SE', 'SWE', 46, 'SEK', 'kr', 'Stockholm'),
(219, 'Switzerland', 'CH', 'CHE', 41, 'CHF', 'CHf', 'Berne'),
(220, 'Syrian Arab Republic', 'SY', 'SYR', 963, 'SYP', 'LS', 'Damascus'),
(221, 'Taiwan, Province of China', 'TW', 'TWN', 886, 'TWD', '$', 'Taipei'),
(222, 'Tajikistan', 'TJ', 'TJK', 992, 'TJS', 'SM', 'Dushanbe'),
(223, 'Tanzania, United Republic of', 'TZ', 'TZA', 255, 'TZS', 'TSh', 'Dodoma'),
(224, 'Thailand', 'TH', 'THA', 66, 'THB', '฿', 'Bangkok'),
(225, 'Timor-Leste', 'TL', 'TLS', 670, 'USD', '$', 'Dili'),
(226, 'Togo', 'TG', 'TGO', 228, 'XOF', 'CFA', 'Lome'),
(227, 'Tokelau', 'TK', 'TKL', 690, 'NZD', '$', ''),
(228, 'Tonga', 'TO', 'TON', 676, 'TOP', '$', 'Nuku\'alofa'),
(229, 'Trinidad and Tobago', 'TT', 'TTO', 1868, 'TTD', '$', 'Port of Spain'),
(230, 'Tunisia', 'TN', 'TUN', 216, 'TND', 'ت.د', 'Tunis'),
(231, 'Turkey', 'TR', 'TUR', 90, 'TRY', '₺', 'Ankara'),
(232, 'Turkmenistan', 'TM', 'TKM', 7370, 'TMT', 'T', 'Ashgabat'),
(233, 'Turks and Caicos Islands', 'TC', 'TCA', 1649, 'USD', '$', 'Cockburn Town'),
(234, 'Tuvalu', 'TV', 'TUV', 688, 'AUD', '$', 'Funafuti'),
(235, 'Uganda', 'UG', 'UGA', 256, 'UGX', 'USh', 'Kampala'),
(236, 'Ukraine', 'UA', 'UKR', 380, 'UAH', '₴', 'Kiev'),
(237, 'United Arab Emirates', 'AE', 'ARE', 971, 'AED', 'إ.د', 'Abu Dhabi'),
(238, 'United Kingdom', 'GB', 'GBR', 44, 'GBP', '£', 'London'),
(239, 'United States', 'US', 'USA', 1, 'USD', '$', 'Washington'),
(240, 'United States Minor Outlying Islands', 'UM', 'UMI', 1, 'USD', '$', ''),
(241, 'Uruguay', 'UY', 'URY', 598, 'UYU', '$', 'Montevideo'),
(242, 'Uzbekistan', 'UZ', 'UZB', 998, 'UZS', 'лв', 'Tashkent'),
(243, 'Vanuatu', 'VU', 'VUT', 678, 'VUV', 'VT', 'Port Vila'),
(244, 'Venezuela', 'VE', 'VEN', 58, 'VEF', 'Bs', 'Caracas'),
(245, 'Viet Nam', 'VN', 'VNM', 84, 'VND', '₫', 'Hanoi'),
(246, 'Virgin Islands, British', 'VG', 'VGB', 1284, 'USD', '$', 'Road Town'),
(247, 'Virgin Islands, U.s.', 'VI', 'VIR', 1340, 'USD', '$', 'Charlotte Amalie'),
(248, 'Wallis and Futuna', 'WF', 'WLF', 681, 'XPF', '₣', 'Mata Utu'),
(249, 'Western Sahara', 'EH', 'ESH', 212, 'MAD', 'MAD', 'El-Aaiun'),
(250, 'Yemen', 'YE', 'YEM', 967, 'YER', '﷼', 'Sanaa'),
(251, 'Zambia', 'ZM', 'ZMB', 260, 'ZMW', 'ZK', 'Lusaka'),
(252, 'Zimbabwe', 'ZW', 'ZWE', 263, 'ZWL', '$', 'Harare');